name: FastAPI CI/CD

on:
  push:
    branches:
      - dev
  
jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.10'

            - name: Install Python Virtual Environment
              run: |
                python -m pip install --upgrade pip
                pip install virtualenv
                virtualenv .venv
                source .venv/bin/activate    

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run tests
              run: |
                pytest

            - name: Create archive of dependencies
              run: |
                zip -r src.zip .venv

            - name: Add API files to ZIP archive
              run: |
                cd ./src
                zip -g ../src.zip -r .
            
            - name: Upload dependencies
              uses: actions/upload-artifact@v4
              with:
                name: src
                path: src.zip

    CD:
        runs-on: ubuntu-latest
        needs: [CI]
        if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
        steps:
        - name: Install AWS CLI
          uses: unfor19/install-aws-cli-action@v1
          with:
            version: 2
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        - name: Download Lambda src.zip
          uses: actions/download-artifact@v4
          with:
            name: src
        - name: Upload to S3
          run: aws s3 cp src.zip s3://lia-handler/src.zip
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        - name: Deploy new Lambda
          run: aws lambda update-function-code --function-name lia-handler-dev --s3-bucket lia-handler --s3-key src.zip
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}