name: FastAPI CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.10'

            - name: Install Python Virtual Environment
              run: |
                python -m pip install --upgrade pip
                pip install virtualenv
                virtualenv venv
                source venv/bin/activate    

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run tests
              run: |
                pytest

            - name: Create archive of dependencies
              run: |
                cd .venv/lib/python3.10/site-packages
                zip -r9 ../../../../dependencies.zip .

            - name: Add API files to archive
              run: |
                cd ./src
                zip -g ../src.zip -r .
            
            - name: Upload dependencies
              uses: actions/upload-artifact@v2
              with:
                name: src
                path: src.zip
